version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: postgres://mirera:your_password@localhost:5432/truckman
    DATABASE_STREAMDATA_URL: postgres://mirera:your_password@localhost:5432/truckman
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme 
    OPBEAT_ENABLED: False

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
