# Generated by Django 4.2.4 on 2023-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logo/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
