# Generated by Django 4.2.4 on 2023-11-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_whatsappsetting_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsetting',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
