# Generated by Django 4.2.4 on 2023-11-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_whatsappsetting_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsetting',
            name='instance_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
