# Generated by Django 4.2.4 on 2023-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='date_added',
        ),
    ]
