# Generated by Django 4.2.4 on 2023-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_department_customuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='Kenya', max_length=30, null=True),
        ),
    ]
