# Generated by Django 4.2.4 on 2024-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_preference_email_from_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='email_from_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='encryption',
            field=models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'NONE')], default='tls', max_length=200),
        ),
    ]
