# Generated by Django 4.2.4 on 2023-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_client_city_alter_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_payment_details',
            field=models.TextField(null=True),
        ),
    ]
