# Generated by Django 4.2.4 on 2023-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_owner',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_owner',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_owner',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
