# Generated by Django 4.2.4 on 2023-08-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='milage_in',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='milage_out',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='milage_unit',
            field=models.CharField(choices=[('kilometers', 'KILOMETERS'), ('miles', 'MILES')], default='kilometers', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='KAM132S', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trailer_number',
            field=models.CharField(default='KAM132D', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='WEDRGT4567', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vehicle_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle_make')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle_make'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle_model'),
        ),
    ]
