# Generated by Django 4.2.4 on 2023-08-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_vehicle_make_vehicle_image_vehicle_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='milage_in',
            new_name='milage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='milage_out',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('operational', 'OPERATIONAL'), ('grounded', 'GROUNDED')], default='operational', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle_make',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_model',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
