# Generated by Django 4.2.4 on 2023-10-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_vehicle_owner_address_vehicle_owner_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='stop_points',
        ),
        migrations.AddField(
            model_name='route',
            name='border_stops',
            field=models.ManyToManyField(blank=True, to='trip.borderstop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop_points',
            field=models.ManyToManyField(blank=True, to='trip.stoppoint'),
        ),
    ]
