# Generated by Django 4.2.4 on 2023-10-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_company'),
        ('trip', '0004_alter_route_distance_alter_route_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderstop',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AddField(
            model_name='stoppoint',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
