# Generated by Django 4.2.4 on 2023-08-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_vehicle_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('id_no', models.CharField(max_length=12)),
                ('dl_no', models.CharField(max_length=12)),
                ('passport_number', models.CharField(max_length=12)),
                ('tel_home', models.CharField(max_length=13)),
                ('tel_roam', models.CharField(max_length=13)),
                ('date_hired', models.DateField()),
                ('date_terminated', models.DateField(blank=True, null=True)),
                ('emergency_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=14, null=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle')),
            ],
        ),
    ]
