# Generated by Django 4.2.4 on 2023-10-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_borderstop_company_stoppoint_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
