# Generated by Django 4.2.4 on 2023-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_driver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_two',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
