# Generated by Django 4.2.4 on 2023-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_driver_emergency_contact_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_passports/'),
        ),
    ]
