# Generated by Django 4.2.4 on 2023-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_alter_route_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='commodity',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='quote_amount',
            field=models.FloatField(null=True),
        ),
    ]
