# Generated by Django 4.2.4 on 2023-08-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_profile_photo'),
        ('trip', '0009_driver_passport_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(blank=True, max_length=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('id_no', models.CharField(blank=True, max_length=12, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=12, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
    ]
