# Generated by Django 4.2.4 on 2023-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id_no',
            new_name='address_one',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='address_two',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='passport_number',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='CU0001', editable=False, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_logo/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_term',
            field=models.CharField(choices=[('operational', 'OPERATIONAL'), ('grounded', 'GROUNDED')], default='2 DAYS', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
