# Generated by Django 4.2.4 on 2023-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_load_commodity_alter_load_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='assigned_trucks',
            field=models.ManyToManyField(to='trip.vehicle'),
        ),
    ]
