# Generated by Django 4.2.4 on 2023-10-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_load_assigned_trucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_odemeter',
        ),
    ]
