# Generated by Django 4.2.4 on 2023-10-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_remove_trip_vehicle_remove_trip_vehicle_odemeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('start_point', models.CharField(max_length=255, null=True)),
                ('midday_location', models.CharField(max_length=255, null=True)),
                ('stop_point', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('morning_odemeter_reading', models.IntegerField(null=True)),
                ('midday_odemeter_reading', models.IntegerField(null=True)),
                ('evening_odemeter_reading', models.IntegerField(null=True)),
                ('vehicle_status', models.CharField(choices=[('Parked', 'Parked'), ('Moving', 'Moving')])),
                ('reason_parked', models.CharField(choices=[('Traffic', 'Traffic'), ('Fuel', 'Fuel'), ('Arrested', 'Arrested'), ('Missing Documentation ', 'Missing Documentation'), ('Missing Documentation Client Side', 'Missing Documentation Client Side')], null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle')),
            ],
        ),
    ]
