# Generated by Django 4.2.4 on 2023-08-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_profile_photo'),
        ('trip', '0013_customer_date_added_alter_customer_address_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_one', models.CharField(blank=True, max_length=50, null=True)),
                ('address_two', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_logo/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('primary_fee', models.FloatField()),
                ('primary_fee_type', models.CharField(choices=[('FLAT FEE', 'Flat Fee'), ('PER MILE', 'Per Mile'), ('PER HUNDRED WEIGHT', 'Per Hundred Weight'), ('PER TON', 'Per Ton'), ('PER QUANTITY', 'Per Quantity')], max_length=30)),
                ('fuel_surcharge_fee', models.FloatField()),
                ('fsc_amount_type', models.CharField(choices=[('FLAT FEE', '2 Days'), ('PER MILE', '7 Days'), ('PER HUNDRED WEIGHT', '10 Days'), ('PER TON', '15 Days'), ('PER QUANTITY', '30 Days')], max_length=30)),
                ('border_agent_fee', models.FloatField()),
                ('road_user', models.FloatField()),
                ('gate_tolls', models.FloatField()),
                ('fines', models.FloatField()),
                ('additional_fees', models.FloatField()),
                ('invoice_advance', models.FloatField()),
                ('legal_disclaimer', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.consignee')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_term',
            field=models.CharField(choices=[('2 DAYS', '2 Days'), ('7 DAYS', '7 Days'), ('10 DAYS', '10 Days'), ('15 DAYS', '15 Days'), ('30 DAYS', '30 Days'), ('Cash on Delivery', 'Cash on Delivery')], default='2 DAYS', max_length=50),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('vehicle_odemeter', models.BigIntegerField()),
                ('driver_accesory_pay', models.IntegerField(null=True)),
                ('driver_advance', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.driver')),
                ('load', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.load')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_one', models.CharField(blank=True, max_length=50, null=True)),
                ('address_two', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_logo/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.customer'),
        ),
        migrations.AddField(
            model_name='load',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.shipper'),
        ),
    ]
