# Generated by Django 4.2.4 on 2023-10-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_dailyregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregister',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.driver'),
        ),
    ]
