# Generated by Django 4.2.4 on 2023-10-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_company'),
        ('trip', '0014_dailyregister_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregister',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
