# Generated by Django 4.2.4 on 2023-08-18 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_consignee_load_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
