# Generated by Django 4.2.4 on 2023-08-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_profile_photo'),
        ('trip', '0016_load_commodity_load_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('sub_total', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('valid_till', models.DateField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('KM', 'Kilometer'), ('MILE', 'Mile'), ('HUNDRED WEIGHT', 'Per Hundred Weight'), ('TON', 'Ton'), ('QUANTITY', 'Quantity')], max_length=20)),
                ('unit', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('paid_on', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('remark', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(to='trip.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip'),
        ),
        migrations.CreateModel(
            name='Expense_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('amount', models.FloatField()),
                ('paid_to', models.CharField(max_length=20)),
                ('date_paid', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('expense_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.expense_category')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_id', models.CharField(editable=False, max_length=7, unique=True)),
                ('sub_total', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('valid_till', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.customer')),
                ('services', models.ManyToManyField(to='trip.service')),
            ],
        ),
    ]
