# Generated by Django 4.2.4 on 2023-10-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_rename_start_point_dailyregister_evening_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyregister',
            name='reason_parked',
            field=models.CharField(blank=True, choices=[('Traffic', 'Traffic'), ('Fuel', 'Fuel'), ('Arrested', 'Arrested'), ('Missing Documentation ', 'Missing Documentation'), ('Missing Documentation Client Side', 'Missing Documentation Client Side')], null=True),
        ),
    ]
