# Generated by Django 4.2.4 on 2023-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_alter_dailyregister_reason_parked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tonnage',
            field=models.IntegerField(null=True),
        ),
    ]
