# Generated by Django 4.2.4 on 2023-08-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_invoice_service_payment_invoice_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='good_transit_licence',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trailer_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trailer_logbook',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_image',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_logbook',
            field=models.ImageField(null=True, upload_to='vehicle_images/'),
        ),
    ]
