# Generated by Django 4.2.4 on 2023-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_remove_vehicle_image_vehicle_good_transit_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='milage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
