# Generated by Django 4.2.4 on 2023-10-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_vehicle_tonnage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadinglistitem',
            name='tonnage',
        ),
        migrations.AddField(
            model_name='loadinglistitem',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.driver'),
        ),
    ]
