# Generated by Django 4.2.4 on 2023-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_alter_vehicle_color_alter_vehicle_milage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passport_photo',
        ),
        migrations.AddField(
            model_name='driver',
            name='dl_back_img',
            field=models.ImageField(null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='dl_front_img',
            field=models.ImageField(null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='dl_issuing_authority',
            field=models.CharField(choices=[('NTSA', 'NTSA'), ('TRA', 'TRA'), ('ZRA', 'ZRA'), ('RRA', 'RRA'), ('URA', 'URA')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(null=True, upload_to='driver_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_person_rlshp',
            field=models.CharField(choices=[('Spouse', 'SPOUSE'), ('Daughter', 'DAUGHTER'), ('Son', 'SON'), ('Mother', 'MOTHER'), ('Father', 'FATHER'), ('Other', 'OTHER')], default='Spouse', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='driver_passports_dl/'),
        ),
    ]
