# Generated by Django 4.2.4 on 2023-08-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_remove_driver_passport_photo_driver_dl_back_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_img',
            field=models.ImageField(null=True, upload_to='driver_photos/'),
        ),
    ]
