# Generated by Django 4.2.4 on 2023-10-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_tripincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripincident',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
