# Generated by Django 4.2.4 on 2023-10-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_tripincident_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripincident',
            name='time_happened',
            field=models.DateTimeField(null=True),
        ),
    ]
