# Generated by Django 4.2.4 on 2023-08-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_profile_photo'),
        ('trip', '0022_remove_load_additional_fees_remove_load_fines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('last_date', models.DateField(null=True)),
                ('next_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Snoozed', 'Snoozed'), ('Active', 'Active'), ('Overdue', 'Overdue'), ('Due', 'Due')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle')),
            ],
        ),
    ]
