# Generated by Django 4.2.4 on 2023-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_alter_tripincident_time_happened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripincident',
            options={'ordering': ['-time_added']},
        ),
        migrations.AddField(
            model_name='customer',
            name='brn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
