# Generated by Django 4.2.4 on 2023-10-30 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_company'),
        ('trip', '0024_alter_tripincident_options_customer_brn_customer_tin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='route',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='trucks',
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(choices=[('Container', 'Container'), ('Loose Cargo', 'Loose Cargo')], default='Container', max_length=20)),
                ('trucks', models.IntegerField(default=0.0)),
                ('rate', models.IntegerField(default=0.0)),
                ('amount', models.IntegerField(default=0.0)),
                ('description', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.estimate')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.route')),
            ],
        ),
    ]
