# Generated by Django 4.2.4 on 2023-10-30 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_remove_estimate_description_remove_estimate_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='trucks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
