# Generated by Django 4.2.4 on 2023-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_alter_estimateitem_amount_alter_estimateitem_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='tel_home',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='driver',
            name='tel_roam',
            field=models.CharField(max_length=12),
        ),
    ]
