# Generated by Django 4.2.4 on 2023-08-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_remove_invoice_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
