# Generated by Django 4.2.4 on 2023-11-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0027_alter_driver_tel_home_alter_driver_tel_roam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='assigned_trucks',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='load',
        ),
        migrations.AddField(
            model_name='load',
            name='assigned_truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.estimate'),
        ),
    ]
