# Generated by Django 4.2.4 on 2023-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_remove_invoice_services_invoice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
