# Generated by Django 4.2.4 on 2023-11-14 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_remove_load_assigned_trucks_remove_trip_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip'),
        ),
    ]
