# Generated by Django 4.2.4 on 2023-11-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0029_load_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='trip',
        ),
    ]
