# Generated by Django 4.2.4 on 2023-08-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0030_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='PA0001', editable=False, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
