# Generated by Django 4.2.4 on 2023-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0030_remove_load_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('Not Loaded', 'Not Loaded'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered')], default='Not Loaded', max_length=50),
        ),
    ]
