# Generated by Django 4.2.4 on 2023-11-15 08:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_whatsappsetting_instance_id'),
        ('trip', '0031_load_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='route',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='trucks',
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(choices=[('Container', 'Container'), ('Loose Cargo', 'Loose Cargo')], default='Container', max_length=20)),
                ('trucks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.invoice')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.route')),
            ],
        ),
    ]
