# Generated by Django 4.2.4 on 2023-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0032_vehicle_is_assigned_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='services',
        ),
        migrations.RemoveField(
            model_name='load',
            name='border_agent_fee',
        ),
        migrations.RemoveField(
            model_name='load',
            name='broker_commission',
        ),
        migrations.RemoveField(
            model_name='load',
            name='fsc_amount_type',
        ),
        migrations.RemoveField(
            model_name='load',
            name='fuel_surcharge_fee',
        ),
        migrations.RemoveField(
            model_name='load',
            name='gate_tolls',
        ),
        migrations.RemoveField(
            model_name='load',
            name='road_user',
        ),
        migrations.AddField(
            model_name='estimate',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='item',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Waiting', 'Waiting'), ('Declined', 'Declined')], default='Waiting', max_length=20),
        ),
    ]
