# Generated by Django 4.2.4 on 2023-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0032_remove_invoice_description_remove_invoice_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='trucks',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
