# Generated by Django 4.2.4 on 2023-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0033_remove_estimate_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
