# Generated by Django 4.2.4 on 2023-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0033_alter_invoice_balance_alter_invoice_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='quote_amount',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_accesory_pay',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_advance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_milage',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='drop_off_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pick_up_location',
        ),
        migrations.AddField(
            model_name='load',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='driver_accesory_pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='driver_advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='driver_milage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='drop_off_location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pick_up_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
