# Generated by Django 4.2.4 on 2023-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0034_remove_load_quote_amount_remove_trip_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_term',
            field=models.CharField(choices=[('2 Days', '2 Days'), ('7 Days', '7 Days'), ('10 Days', '10 Days'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('Cash on Delivery', 'Cash on Delivery')], default='2 DAYS', max_length=50),
        ),
    ]
