# Generated by Django 4.2.4 on 2023-08-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0035_estimate_quantity_estimate_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='primary_fee',
        ),
        migrations.RemoveField(
            model_name='load',
            name='primary_fee_type',
        ),
        migrations.AddField(
            model_name='load',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.estimate'),
        ),
    ]
