# Generated by Django 4.2.4 on 2023-08-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0036_remove_load_primary_fee_remove_load_primary_fee_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='invoice_advance',
            new_name='quote_amount',
        ),
    ]
