# Generated by Django 4.2.4 on 2023-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0037_load_date_loaded_load_date_offloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tracking_uri',
            field=models.URLField(null=True),
        ),
    ]
