# Generated by Django 4.2.4 on 2023-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0038_remove_load_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.IntegerField(default=0.0),
        ),
    ]
