# Generated by Django 4.2.4 on 2023-12-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0039_alter_dailyregister_reason_parked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='truck_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_used', to='trip.vehicle'),
        ),
    ]
