# Generated by Django 4.2.4 on 2024-01-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0040_load_truck_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_paid']},
        ),
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_on']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-date_added']},
        ),
    ]
