# Generated by Django 4.2.4 on 2023-08-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0041_alter_driver_assigned_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle'),
        ),
    ]
