# Generated by Django 4.2.4 on 2023-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0042_alter_driver_assigned_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_off_location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pick_up_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
