# Generated by Django 4.2.4 on 2023-09-04 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_dark_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0044_alter_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('warning', 'warning'), ('success', 'success'), ('danger', 'danger'), ('info', 'info'), ('stateless', 'stateless')], default='info', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
