# Generated by Django 4.2.4 on 2023-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0045_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dl_back_img',
            field=models.FileField(null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dl_front_img',
            field=models.FileField(null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_image',
            field=models.FileField(null=True, upload_to='driver_passports_dl/'),
        ),
    ]
