# Generated by Django 4.2.4 on 2023-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0046_alter_driver_dl_back_img_alter_driver_dl_front_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='good_transit_licence',
            field=models.FileField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trailer_image',
            field=models.FileField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trailer_logbook',
            field=models.FileField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_image',
            field=models.FileField(null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_logbook',
            field=models.FileField(null=True, upload_to='vehicle_images/'),
        ),
    ]
