# Generated by Django 4.2.4 on 2023-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0047_alter_vehicle_good_transit_licence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dl_back_img',
            field=models.FileField(blank=True, null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='dl_front_img',
            field=models.FileField(blank=True, null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id_img',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_image',
            field=models.FileField(blank=True, null=True, upload_to='driver_passports_dl/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='good_transit_licence',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trailer_image',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trailer_logbook',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_image',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_logbook',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
