# Generated by Django 4.2.4 on 2023-09-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0048_alter_driver_dl_back_img_alter_driver_dl_front_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vin',
            new_name='truck_vin',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trailer_vin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
