# Generated by Django 4.2.4 on 2023-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0049_rename_vin_vehicle_truck_vin_vehicle_trailer_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='emergency_contact_two',
            new_name='emergency_contact_no_three',
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_no_two',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_person_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_person_three_rlshp',
            field=models.CharField(choices=[('Spouse', 'SPOUSE'), ('Daughter', 'DAUGHTER'), ('Son', 'SON'), ('Mother', 'MOTHER'), ('Father', 'FATHER'), ('Other', 'OTHER')], default='Spouse', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_person_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_person_two_rlshp',
            field=models.CharField(choices=[('Spouse', 'SPOUSE'), ('Daughter', 'DAUGHTER'), ('Son', 'SON'), ('Mother', 'MOTHER'), ('Father', 'FATHER'), ('Other', 'OTHER')], default='Spouse', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('On Probation', 'On Probation'), ('Permanent', 'Permanent'), ('On Contract', 'On Contract')], default='On Probation', max_length=20),
        ),
    ]
