# Generated by Django 4.2.4 on 2023-09-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0050_rename_emergency_contact_two_driver_emergency_contact_no_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='trailer_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
