# Generated by Django 4.2.4 on 2023-09-25 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0054_trip_end_time_trip_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle'),
        ),
    ]
