# Generated by Django 4.2.4 on 2023-09-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0056_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='quantity',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='unit_price',
            new_name='trucks',
        ),
        migrations.AddField(
            model_name='estimate',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.route'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='item',
            field=models.CharField(choices=[('Container', 'Container'), ('Loose Cargo', 'Loose Cargo')], default='Container', max_length=20),
        ),
    ]
